### ISSUE TITLE
Concerns about google screenshots in docs

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-docs#21]
@ngehlenborg writes on PR hubmapconsortium/portal-ui#592:
> @schwenk102 @pecan88 I have a content concern: this image is a screenshot that someone grabbed from a Google search. We can't just make that part of our documentation, it could get us into legal trouble.

in seqfish.md:
```
![](https://lh3.googleusercontent.com/oHCVhh_9ZeoqRhEcflRjARPAdtxRCs1-lC2W4X_WNX-fBFYDC0tbkL2hDrrXVvvUGc0BVF-0eaYoi4jr0XRNz_QbcrDB4UWQjSnIHQNrtxkS97ZBnKQkkfYilBaGxOFzz6CFh-s)
```

**Comment by pecan88** [comment]
What are the next steps needed to close this?  Or is this still an issue?

If this is assay documentation specific, I would suggest @cebriggs7135 reach out to Nico of Caltech to identify a more appropriately shareable image.  I defer to Nils' greater expertise re: the legal / copyright considerations around use of images.
