### ISSUE TITLE
add team overview to "About" page

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-docs#22]
Section to the added to the “About” page (https://portal.hubmapconsortium.org/docs/about) above Software, below Contact:

https://docs.google.com/document/d/1WmwaDJUc2UxX8leWtw8E48bpyDUodzGuVhSGOuy6Wj4/edit?ts=5f58e7bc

**Comment by pecan88** [comment]
@schwenk102 - would you please make the adjustments in the appropriate markdown file and submit a PR?

**Comment by mccalluc** [comment]
I fixed in #34. Closing.
