### ISSUE TITLE
Removed reference to MxIF from the MALDI document

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/portal-docs#25]
@mccalluc The directory structure section of the MALDI doc on the portal:
https://portal.hubmapconsortium.org/docs/assays/maldi-ims

has the word MxIF in the title:
![Screen Shot 2020-09-24 at 6 37 19 PM](https://user-images.githubusercontent.com/8284878/94207199-17bbfe80-fe95-11ea-8ff9-e496e2853f4e.png)

I fixed it.

**Comment by mccalluc** [comment]
Great -- Is there anything you need me to do? Issues remind us of work that needs to be done -- but you've just fixed it. Closing.
