### ISSUE TITLE
Donor Metadata Specification link is broken

### ISSUE THREAD

**Issue by cebriggs7135** [hubmapconsortium/portal-docs#26]
From here:
https://github.com/hubmapconsortium/portal-docs/blob/master/metadata.md
The Donor Metadata Specification link is broken:
![Screen Shot 2020-10-22 at 9 56 57 AM](https://user-images.githubusercontent.com/8284878/96882382-3dfd9b80-144d-11eb-8c84-2fd599a31eca.png)

**Comment by mccalluc** [comment]
@cebriggs7135 : For links to work on the site, they should be of the form `/docs/*` with no `.md` ... that is in tension with the what we'd want to make them work just inside github. We can't have both working at the same time.
