### ISSUE TITLE
broken link on FAQ page

### ISSUE THREAD

**Issue by smrgit** [hubmapconsortium/portal-docs#27]
the link attached to the words "donor metadata, sample metadata, and assay metadata" leads to a 404 page

it currently links to: https://github.com/hubmapconsortium/portal-docs/blob/master/docs/metadata 

probably should link to this instead: https://github.com/hubmapconsortium/portal-docs/blob/master/metadata.md

**Comment by smrgit** [comment]
follow-up -- the links on the Metadata page also appear to be broken, eg:
https://github.com/hubmapconsortium/portal-docs/blob/master/docs/assays/mxif 
instead of:
https://github.com/hubmapconsortium/portal-docs/blob/master/assays/mxif.md

**Comment by pecan88** [comment]
@mccalluc  & @ngehlenborg - what is the default behavior or expectation for developers using GitHub re: links within GitHub entries?  Would a developer expect the links to go to the appropriate content, or would they understand that the content is being deployed to a different site which would affect the URL structure?

My default would be to have it link to the appropriate content, however I want to make sure we're sticking to whatever norms there are in a developer-focused environment like GitHub ... so, requesting your guidance here.  Also looping in @schwenk102 for whatever final decisions we make in case we need to make markdown specific changes.

**Comment by mccalluc** [comment]
This repo is mirrored into https://portal.hubmapconsortium.org/docs/ ... and in that context, we don't want the urls to include `.md`. (On the portal, the extension would be an implementation detail that shouldn't be exposed to users.)

But, at the same same time, when someone clicks on a link, in any context, they expect it to work.

But there are some links here that are never going to work in github, like
```
./faq.md:The Portal is available at [portal.hubmapconsortium.org](/)
```
Similarly if there were links to the search pages, or other parts of the site.... So the goal of having links be usable in the context of github is never going to hold 100%.

Options:
- 👎 Show `.md` in URLs on the portal. 
- 👎 Tricky development work to strip `.md` when rendering in the portal. 
-  🤷 Make the repo private? Except for contributors, folks should just look at the portal?
- 🤷  Add a note on each page that makes the same explanation, in a way that will be hidden when rendered on the portal. 
- 👍 Note on the README with the explanation above.
