### ISSUE TITLE
/docs/submission is inaccurate; should be deleted

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-docs#39]
The information is out of date and inaccurate. The page should be removed, and for questions about submission users should be directed to https://github.com/hubmapconsortium/ingest-validation-tools and https://ingest.hubmapconsortium.org/... and if the information there isn't sufficient, the gaps should be identified.

**Comment by cebriggs7135** [comment]
@mccalluc Can you please put the link to the document you'r referring to here?

**Comment by mccalluc** [comment]
@cebriggs7135 https://portal.hubmapconsortium.org/docs/submission
