### ISSUE TITLE
NIH request for Portal preview of ASCT+B tables

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/portal-docs#52]
We were thinking it would be good to have a more lay friendly description of the ASCT+B tables on the website.
Can you please put this language in for the ASCT+B tables on the preview page on the Data Portal? Ajay would like to show it as part of a presentation next week.
If you guys can make that happen, it'd be great!
Thanks so much!
Dena

[CCF description.docx](https://github.com/hubmapconsortium/portal-docs/files/5966241/CCF.description.docx)

**Comment by mccalluc** [comment]
portal-ui issue opened.
