### ISSUE TITLE
typos/update asset urls in documentation pages

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/portal-docs#64]
HuBMAP: typos/update asset urls in documentation pages

Hi All,

Talked to Chris Briggs and she said to send message here for typos or updating links to assets in the documentation pages on Data Portal.

=========
From Data portal page: https://portal.hubmapconsortium.org/docs/software

IVMOOC should be VHMOOC, the link is correct; IV—> VH stands for Visible Human

=========
FROM Data Portal page: https://portal.hubmapconsortium.org/docs/software CCF registration tool (RUI) link to our OLD RUI
GitHub: ccf-3d-registration https://github.com/hubmapconsortium/ccf-3d-registration#readme
The updated RUI and EUI are combined here when RUI was updated to new platform and to incorporate new organs:
ccf-ui https://github.com/hubmapconsortium/ccf-ui
========
FROM Data Portal page: https://portal.hubmapconsortium.org/docs/software CCF reference objects (body, organs) link to our live and evolving 3D ref models on GitHub here:https://github.com/hubmapconsortium/ccf-3d-reference-object-library#readme
As per Katy, We would prefer the DOI published version of the 3D ref organs to be linked asset here:
https://hubmapconsortium.github.io/ccf/pages/ccf-3d-reference-library.html

============
Additionally on this page: https://github.com/hubmapconsortium/ontology-api#readme

The user can "walk" backbone of the graph in a vocabulary agnostic manner and/or branch off into specific vocabularies.

vocabularies. should be vocabularies.

============

Ellen

Ellen M. Quardokus

**Comment by cebriggs7135** [comment]
Setting up a meeting with Ellen Q to go over the corrections requested/suggested.

**Comment by cebriggs7135** [comment]
Fixed the first one: IVMOOC should be VHMOOC, the link is correct; IV—> VH stands for Visible Human

**Comment by cebriggs7135** [comment]
All 3 are resolved.
