### ISSUE TITLE
Update WGS contact from Aaron Horning to Annika Weimer

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-docs#68]
Please update [on the metadata page ](https://portal.hubmapconsortium.org/docs/metadata)the contact person from Aaron Horning (who is departing HuBMAP) to Annika Weimer (aweimer@stanford.edu).

**Comment by cebriggs7135** [comment]
@pecan88 Made this edit on 080521. Will check on Friday to see if it's merged and on the portal yet.
