### ISSUE TITLE
Rename "assay/" to "assays/"

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-docs#8]
People expect that when they shorten a URL they get a higher level page. Right now we have "docs/assay" and "docs/assay<b>s</b>/af", etc. Suggest retitling either the directory or the file to be consistent.

**Comment by cebriggs7135** [comment]
@mccalluc I don't see /assays. Where is that?
![Screen Shot 2020-07-28 at 4 17 11 PM](https://user-images.githubusercontent.com/8284878/88716986-d950d000-d0ed-11ea-8887-a3a2e777c051.png)

**Comment by mccalluc** [comment]
Sorry, other way around. File is `assays.md`; directory is `assay`; Better to have them consistent.
